apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder-arbeidsforhold
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-arbeidsforhold-db-instance
        type: POSTGRES_15
        diskSize: 10
        databases:
          - name: narmesteleder-arbeidsforhold
            envVarPrefix: NAIS_DATABASE
        tier: db-f1-micro
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 40m
      memory: 450Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: aareg-services-q1.dev-fss-pub.nais.io
  env:
    - name: AAREG_URL
      value: https://aareg-services-q1.dev-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
