apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: narmesteleder-arbeidsforhold
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: narmesteleder-arbeidsforhold-db-instance
        type: POSTGRES_12
        diskSize: 10
        databases:
          - name: narmesteleder-arbeidsforhold
            envVarPrefix: NAIS_DATABASE
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  webproxy: true
  kafka:
    pool: nav-prod
